name: Build Flet APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
          
      - name: Instalar dependências e build
        run: |
          pip install flet
          flet build apk --module-name main
          
      - uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: build/apk/app-release.apk
