name: Build Flet APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: 1 # Isso ajuda a evitar erros de leitura de stream
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
     - name: Build APK
        run: |
          pip install flet
          mkdir -p assets
          cp filtros_wega.db assets/ || true
          # Adicionamos -v para modo verbose (detalhado)
          flet build apk --module-name main -v
      - uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: build/apk/app-release.apk
